### PR TITLE
[Wallet] Fix linking errors on iOS with latest @celo/client and release builds

### LINKED ISSUE #4781: React native geth linking error in production iOS build
### Expected Behavior

Linking react native geth behaves the same in dev and production builds, and it works with the latest @celo/client 0.0.315

### Current Behavior

When creating a production build of iOS, react native geth with @celo/client 0.0.315 throws the following error: 
`Linking react_native_geth
[17:08:32]: ▸ ❌  Undefined symbols for architecture armv7
[17:08:32]: ▸ > Symbol: _GethLightScryptP
[17:08:32]: ▸ > Referenced from: react_native_geth.RNGeth.nodeConfig(config: __C.NSDictionary?, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in RNGeth-dcd80422d643460b9393c5fd49178a60253565ed458f1ce46f9e38f260bba0a2.o
[17:08:32]: ▸ ❌  ld: symbol(s) not found for architecture armv7
[17:08:32]: ▸ ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[17:08:32]: ▸ Linking react_native_geth
[17:08:32]: ▸ ** ARCHIVE FAILED **
[17:08:32]: ▸ The following build commands failed:
[17:08:32]: ▸ 	Ld /Users/annakaz/Library/Developer/Xcode/DerivedData/celo-hbrdjyegktphzlaszuhudanoaxha/Build/Intermediates.noindex/ArchiveIntermediates/celo-mainnet/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/react-native-geth.build/Objects-normal/armv7/Binary/react_native_geth normal armv7
[17:08:32]: ▸ (1 failure)`

To reproduce, run `fastlane ios build env:mainnet`

This issue does not reproduce in dev builds

Labeled as p1, not p0, as @celo/client 0.0.309 is compatible with the current build and can be used for the upcoming release

### PR DESCRIPTION
**Pull request by jeanregisser**
### Description

Latest `@celo/client` doesn't contain 32 bits archs anymore (we don't need them on iOS >= 11), however main Pods project was still compiled against iOS 9.0, so triggered an error on release builds.

### Other changes

- Fix "ld: framework not found Pods_celoTests" when trying to run release build from Xcode

### Tested

Release builds work on iOS.

### Related issues

- Fixes #4781

### Backwards compatibility

Yes

### CODE REVIEW

**Review by gnardini — APPROVED** [review]

**Comment by Lss-Ankit** [comment]
Hi @jeanregisser i have verified task using latest Android internal build v1.1.0  (1004294309) and Test flight build v1.1.0 (21) and able to install build on above 12.4 devices. 

Note: i have checked below 12.4 device and it is shows pop up " This application requires IOS 12.4 or latter" 

can you please let me know if i need to verify any thing else. 
thanks !
