### ISSUE TITLE
React native geth linking error in production iOS build

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4781]
### Expected Behavior

Linking react native geth behaves the same in dev and production builds, and it works with the latest @celo/client 0.0.315

### Current Behavior

When creating a production build of iOS, react native geth with @celo/client 0.0.315 throws the following error: 
`Linking react_native_geth
[17:08:32]: ▸ ❌  Undefined symbols for architecture armv7
[17:08:32]: ▸ > Symbol: _GethLightScryptP
[17:08:32]: ▸ > Referenced from: react_native_geth.RNGeth.nodeConfig(config: __C.NSDictionary?, resolver: (Any?) -> (), rejecter: (Swift.String?, Swift.String?, Swift.Error?) -> ()) -> () in RNGeth-dcd80422d643460b9393c5fd49178a60253565ed458f1ce46f9e38f260bba0a2.o
[17:08:32]: ▸ ❌  ld: symbol(s) not found for architecture armv7
[17:08:32]: ▸ ❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
[17:08:32]: ▸ Linking react_native_geth
[17:08:32]: ▸ ** ARCHIVE FAILED **
[17:08:32]: ▸ The following build commands failed:
[17:08:32]: ▸ 	Ld /Users/annakaz/Library/Developer/Xcode/DerivedData/celo-hbrdjyegktphzlaszuhudanoaxha/Build/Intermediates.noindex/ArchiveIntermediates/celo-mainnet/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/react-native-geth.build/Objects-normal/armv7/Binary/react_native_geth normal armv7
[17:08:32]: ▸ (1 failure)`

To reproduce, run `fastlane ios build env:mainnet`

This issue does not reproduce in dev builds

Labeled as p1, not p0, as @celo/client 0.0.309 is compatible with the current build and can be used for the upcoming release
