### PR TITLE
[cli] Solution for build error contractkit on Linux 19.04 distro

### PR DESCRIPTION
**Pull request by diminator**
### Description

Solution to build error `cannot find module @celo/contractkit`

### Tested

Works on Linux 19.04 distro

### Related issues

No issue was created

### CODE REVIEW

File: packages/cli/README.md [hunk 1]
```diff
@@ -4,10 +4,27 @@ Tool for interacting with the Celo Protocol.
...
 Use `yarn build` to compile the CLI.
 
+> I'm getting the follow error: `Cannot find module '@celo/contractkit'`.
+>
+> What to do?
+
+A possible solution is to build `contractkit` manually from the monorepo.
+
+```bash
+> cd ../contractkit
```
Comment (ashishb) [inline packages/cli/README.md]: `cd ../contractkit` - it is not clear which dir you are in at this point.

**Review by ashishb — APPROVED** [review]

File: packages/cli/README.md [hunk 2]
```diff
@@ -4,10 +4,67 @@ Tool for interacting with the Celo Protocol.
...
+If all works well, navigate to `packages/cli`.
+
+> I'm getting the follow error during the above build: `lerna ERR! yarn run build exited 1 in '@celo/protocol'`.
+
+This error implies that the `truffle` project is not initialized.
+Navigate to `celo-monorepo/packages/protocol` and initialize the truffle project.
+Make sure you do NOT overwrite any existing contracts, migrations or tests.
+
+```bash
+> npm i -g truffle
```
Comment (mcortesi) [inline packages/cli/README.md]: this sounds weird...
why would you need to initialize truffle?

Do you have a more specific error log?

**Review by mcortesi — CHANGES_REQUESTED** [review]

File: packages/cli/README.md (hunk 2 above)
Comment (diminator) [reply packages/cli/README.md]: `node v8.16.1`
`Linux dimi-xps 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
`

```
> git clone git@github.com:celo-org/celo-monorepo.git
> yarn
> cd packages/protocol/
> yarn build
```

```
yarn run v1.17.3
$ ts-node ./scripts/build.ts && yarn build:ts
Compiling
Warning: Both truffle-config.js and truffle.js were found. Using truffle-config.js.

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

{ Error: ENOENT: no such file or directory, open '/home/dimi/celo/celo-monorepo-test/packages/protocol/build/contracts/Proxy.json'
```

Observations:
- Truffle doesn't recognize the `contracts` directory
- Truffle is finding some `truffle-config.js` (there's a few in the `node_modules`, maybe somewhere else on my system)

Comment (diminator) [reply packages/cli/README.md]: renaming `protocol/truffle.js` to `protocol/truffle-config.js` is a potential fix

Comment (mcortesi) [reply packages/cli/README.md]: that sounds more reasonable.
Still is strange that none other has the same issue... are you using `yarn` or `npm`?

Comment (diminator) [reply packages/cli/README.md]:
```
> yarn
> cd packages/protocol/
> yarn build
```

Comment (diminator) [reply packages/cli/README.md]: maybe you can test by adding an empty `truffle-config.js` and try building?

so you can see if your `truffle` is also having that config pref

Comment (mcortesi) [reply packages/cli/README.md]: sorry a bit confused here

we started by saying that we need to do `truffle init` to make the repo build on linux. That's what i found strange. Surely the truffle-config.js is a result of running `init`, right?

Comment (diminator) [reply packages/cli/README.md]: I understand the confusion. Forget about the `truffle init` solution.

When I do a vanilla `yarn && yarn build` on the repo I get the error. So without `init`.
Seems that `truffle` finds somewhere `truffle-config.js` it will prefer that one over the existing `truffle.js`. That seems to be the case for me.

Comment (diminator) [reply packages/cli/README.md]: Not sure if it's an actual issue or just something on my local device due to previous projects using ganache

**Comment by diminator** [comment]
@mcortesi I reframed the error. Is this good to go?

**Review by mcortesi — APPROVED** [review]
approved...

but can't we just change  truffle.js to truffle-config.js?

**Comment by diminator** [comment]
> approved...
> 
> but can't we just change truffle.js to truffle-config.js?

that would be too easy :)

**Comment by diminator** [comment]
I'm thinking all of the build issues were due to not finding the right `truffle-config.js`. Means `yarn build` failed there and `contractkit didn't get build`

**Review by mcortesi — APPROVED** [review]
Awesome!
